### ISSUE TITLE
Support Clipboard for TextInputControl

### ISSUE THREAD

**Issue by hsiafan** [gluonhq/gluonfx-maven-plugin#111]
I'm using client-maven-plugin 0.1.12, with openjfx version 13.0.1, on OSX 10.15.1.
It seems that javafx Clipboard not work for TextInputControls, such as TextArea, TextField.  Both context menu and  schortcuts(CMD+V/CMD+C) throws exceptions:
```
Exception in thread "JavaFX Application Thread" java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.input.Clipboard
    at com.sun.javafx.util.Utils.forceInit(Utils.java:858)
    at com.sun.javafx.scene.input.ClipboardHelper.<clinit>(ClipboardHelper.java:39)
    at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
    at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
    at java.lang.Class.ensureInitialized(DynamicHub.java:475)
    at javafx.scene.input.Clipboard.<clinit>(Clipboard.java:141)
    at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
    at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
    at java.lang.Class.ensureInitialized(DynamicHub.java:475)
    at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.populateContextMenu(TextInputControlBehavior.java:700)
    at com.sun.javafx.scene.control.behavior.TextFieldBehavior.contextMenuRequested(TextFieldBehavior.java:377)
    at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene.processMenuEvent(Scene.java:1889)
    at javafx.scene.Scene$ScenePeerListener.menuEvent(Scene.java:2612)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$3(GlassViewEventHandler.java:484)
    at java.security.AccessController.doPrivileged(AccessController.java:98)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$4(GlassViewEventHandler.java:464)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMenuEvent(GlassViewEventHandler.java:463)
    at com.sun.glass.ui.View.handleMenuEvent(View.java:564)
    at com.sun.glass.ui.View.notifyMenu(View.java:894)
    at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Lcom_sun_glass_ui_View_2_0002enotifyMenu_00028IIIIZ_00029V(JNIJavaCallWrappers.java:0)
Caused by: java.lang.ClassNotFoundException: javafx.scene.input.Clipboard
    at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
    at java.lang.Class.forName(DynamicHub.java:1197)
    at com.sun.javafx.util.Utils.forceInit(Utils.java:855)
    ... 37 more
```

I try to add reflect and jni list to maven config:
```xml
<reflectionList>
    <list>javafx.scene.input.Clipboard</list>
</reflectionList>
<jniList>
    <list>com.sun.glass.ui.mac.MacPasteboard</list>
</jniList>
```

but another ClassCastException is thrown:
```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException
    at com.oracle.svm.jni.JNIThreadLocalPendingException.set(JNIThreadLocalPendingException.java:42)
    at com.oracle.svm.jni.JNIThreadLocalPendingException.clear(JNIThreadLocalPendingException.java:45)
    at com.oracle.svm.jni.JNIGeneratedMethodSupport.getAndClearPendingException(JNIGeneratedMethodSupport.java:98)
    at com.oracle.svm.jni.JNIGeneratedMethodSupport.rethrowPendingException(JNIGeneratedMethodSupport.java:103)
    at com.sun.glass.ui.mac.MacPasteboard._getUTFs(MacPasteboard.java)
    at com.sun.glass.ui.mac.MacPasteboard.getUTFs(MacPasteboard.java:101)
    at com.sun.glass.ui.mac.MacSystemClipboard.mimesFromSystem(MacSystemClipboard.java:317)
    at com.sun.glass.ui.SystemClipboard.getMimeTypes(SystemClipboard.java:84)
    at com.sun.glass.ui.ClipboardAssistance.getMimeTypes(ClipboardAssistance.java:140)
    at com.sun.javafx.tk.quantum.QuantumClipboard.hasContent(QuantumClipboard.java:513)
    at javafx.scene.input.Clipboard.hasContent(Clipboard.java:294)
    at javafx.scene.input.Clipboard.hasString(Clipboard.java:303)
    at javafx.scene.control.TextInputControl.paste(TextInputControl.java:656)
    at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.paste(TextInputControlBehavior.java:528)
    at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$new$20(TextInputControlBehavior.java:159)
    at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:330)
    at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$KeyHandler.process(Scene.java:4070)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2597)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.security.AccessController.doPrivileged(AccessController.java:98)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at com.sun.glass.ui.View.notifyKey(View.java:971)
    at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Lcom_sun_glass_ui_View_2_0002enotifyKey_00028II_3CI_00029V(JNIJavaCallWrappers.java:0)
```

Clipboard should be support by default, as it provide  necessary function for TextInputs. 
And any ideas to get rid of ClassCastException thrown when add MacPasteboard to jni list?

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with a recent version of the plugin (latest is 1.0.10). Feel free to reopen otherwise.
