### ISSUE TITLE
IllegalStateException for legal state

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#113]
In my test programs I occasionally get the following exception when I exit the program via Platform.exit. (Something like `quitButton.setOnAction(ev -> Platform.exit());`)
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:291)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:446)
	at javafx.stage.Window.setShowing(Window.java:1173)
	at javafx.stage.Window.hide(Window.java:1199)
	at com.sun.javafx.stage.WindowPeerListener.closed(WindowPeerListener.java:105)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:144)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(AccessController.java:99)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1351)
	at com.sun.glass.ui.Window.notifyDestroy(Window.java:1260)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Lcom_sun_glass_ui_Window_2_0002enotifyDestroy_00028_00029V(JNIJavaCallWrappers.java:0)
```
This is strange because the exception complains about "Not on FX application thread" but at the same time states that the "currentThread = JavaFX Application Thread". This happens only occasionally - let's say 1 out of 10 runs of the same build. So, this is probably a timing issue somewhere. It is not critical but I just wanted to let you know that there is an issue. I can't provide a demo for this because I haven't observed this behavior in any small hello-world program yet.

Environment:
macOS 10.14.6
GraalVM CE 11 19.3.1
OpenJFX 14-ea+7
client-maven-plugin 0.1.12

**Comment by jperedadnr** [comment]
Yes, I've noticed this from time to time too.

**Comment by jperedadnr** [comment]
I don't think this is an issue anymore. Feel free to reopen if you still get it.
