### ISSUE TITLE
Program crashes when selecting file in filechooser

### ISSUE THREAD

**Issue by NO-ob** [gluonhq/gluonfx-maven-plugin#121]
It works fine in java and opens when compiled for native but throws this exception when selecting a file
```
(Mascot:4891): Gtk-CRITICAL **: 19:10:06.403: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Lcom/sun/glass/ui/CommonDialogs;
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:316)
        at com.sun.glass.ui.gtk.GtkCommonDialogs._showFileChooser(GtkCommonDialogs.java)
        at com.sun.glass.ui.gtk.GtkCommonDialogs.showFileChooser(GtkCommonDialogs.java:58)
        at com.sun.glass.ui.gtk.GtkApplication.staticCommonDialogs_showFileChooser(GtkApplication.java:448)
        at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:213)
        at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1579)
        at javafx.stage.FileChooser.showDialog(FileChooser.java:413)
        at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:348)
        at Mascot.MascotController.openImage(MascotController.java:72)
        at Mascot.MascotController.setStage(MascotController.java:64)
        at Mascot.Main.start(Main.java:28)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.security.AccessController.doPrivileged(AccessController.java:98)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.oracle.svm.jni.access.JNIReflectionDictionary.findMethod(JNIReflectionDictionary.java:161)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getMethodID(JNIReflectionDictionary.java:202)
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1016)
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1012)
        at com.oracle.svm.jni.functions.JNIFunctions.GetStaticMethodID(JNIFunctions.java:378)
        at com.sun.glass.ui.gtk.GtkCommonDialogs._showFileChooser(GtkCommonDialogs.java)
        at com.sun.glass.ui.gtk.GtkCommonDialogs.showFileChooser(GtkCommonDialogs.java:58)
        at com.sun.glass.ui.gtk.GtkApplication.staticCommonDialogs_showFileChooser(GtkApplication.java:448)
        at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:213)
        at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1579)
        at javafx.stage.FileChooser.showDialog(FileChooser.java:413)
        at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:348)
        at Mascot.MascotController.openImage(MascotController.java:72)
        at Mascot.MascotController.setStage(MascotController.java:64)
        at Mascot.Main.start(Main.java:28)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.security.AccessController.doPrivileged(AccessController.java:98)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by mipastgt** [comment]
This type of error can often be cured by adding the missing class to the reflection list inside the plugin configuration.
```
<reflectionList>
   <list>com.sun.glass.ui.CommonDialogs</list>
</reflectionList>
```
If that does not help, try the jniList instead.

**Comment by NO-ob** [comment]
Even with that link i still get ```Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Lcom/sun/glass/ui/CommonDialogs;```

**Comment by graynk** [comment]
This is what I get with latest GraalVM (both official 21.2.0 and the gluon build):
```
./sie                                                                                                    ⏎
Sep 12, 2021 6:23:47 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @37af1f93'
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: java.lang.String.<init>([B)V
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1104)
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1089)
	at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:410)
	at com.sun.glass.ui.gtk.GtkCommonDialogs._showFileChooser(GtkCommonDialogs.java)
	at com.sun.glass.ui.gtk.GtkCommonDialogs.showFileChooser(GtkCommonDialogs.java:58)
	at com.sun.glass.ui.gtk.GtkApplication.staticCommonDialogs_showFileChooser(GtkApplication.java:461)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:213)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1717)
	at javafx.stage.FileChooser.showDialog(FileChooser.java:419)
	at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:354)
	at space.graynk.sie.SieController.onOpenFile(SieController.java:100)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1854)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1724)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3880)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1873)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2606)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.security.AccessController.doPrivileged(AccessController.java:105)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:423)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
	at com.sun.glass.ui.View.notifyMouse(View.java:943)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWrappers.java:0)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:552)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
[1]    18633 segmentation fault (core dumped)  ./sie
```
Adding classes mentioned in the stacktrace to `reflectionList` and `jniList` did not help.

Tangential question: the documentation for the plugin says that `reflectionList` "already includes most of the JavaFX classes", however I still had to manually add most of the classes that my project uses. I also use Java Modules, is this the reason?

**Comment by graynk** [comment]
After fixing versions in pom.xml to
```
<javaStaticSdkVersion>11.0.12</javaStaticSdkVersion>
<javafxStaticSdkVersion>17-ea+11</javafxStaticSdkVersion>
```
it started working for some reason. Couldn't tell you why

**Comment by jperedadnr** [comment]
Mostly due to more classes/methods added to the reflection/jni lists that the plugin adds internally.
