### ISSUE TITLE
java.util.logging FileHandler does not work

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#125]
I am using Java logging which workes nicely so far. I now tried to add a FileHandler but I only get the following exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: jdk.internal.misc.VM.getuid()J [symbol: Java_jdk_internal_misc_VM_getuid or Java_jdk_internal_misc_VM_getuid__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at jdk.internal.misc.VM.getuid(VM.java)
	at jdk.internal.misc.VM.isSetUID(VM.java:336)
	at java.util.logging.FileHandler.generate(FileHandler.java:661)
	at java.util.logging.FileHandler.generate(FileHandler.java:621)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:493)
	at java.util.logging.FileHandler.<init>(FileHandler.java:307)
```
Even if I create the file handler explicitly via `new FileHandler(<some file pattern>)` I only get the above execption. Adding `jdk.internal.misc.VM` to the reflection or JNI list also does not make any difference.

macOS 10.14.6
GraalVM 19.3.1
client-maven-plugin 0.1.15
jfx 15-ea+1

**Comment by jperedadnr** [comment]
I'm not sure if this is still an issue. Feel free to reopen again proving a reproducible case.
