### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.sun.glass.ui.mac.MacAccessible

### ISSUE THREAD

**Issue by zboigor** [gluonhq/gluonfx-maven-plugin#189]
I get `NoClassDefFoundError: Could not initialize class com.sun.glass.ui.mac.MacAccessible` error while running HelloFX sample from [client-samples](https://github.com/gluonhq/client-samples/).
Full stacktrace is here: [https://pastebin.com/Z74deJ59](https://pastebin.com/Z74deJ59)

MacOS Catalina 10.15.5
GraalVM CE 20.2.0-dev-20200605_0158 (from graalvm-ce-java11-darwin-amd64-20.2.0-dev.tar.gz)
Client plugin version: 0.1.27

**Comment by cavoirom** [comment]
Faced the same error when building the <https://github.com/gluonhq/gluon-samples/tree/master/HelloFX>

MacOS Monterey 12.6 (Apple Silicon)
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

```
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.glass.ui.mac.MacAccessible
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at com.sun.glass.ui.mac.MacApplication.createAccessible(MacApplication.java:307)
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at javafx.scene.Scene.getAccessible(Scene.java:6460)
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2886)
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1390)
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at com.sun.glass.ui.View.getAccessible(View.java:1112)
[Sun Oct 16 12:31:03 ICT 2022][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_View_getAccessible_208bf9d5e8902251a899fb9f0c818944d597913d(JNIJavaCallWrappers.java:0)
```

**Comment by taranion** [comment]
I ran into that as well. The UI itself seems to work, but there are lot of that stack traces on the console.

**Comment by ctoabidmaqbool1** [comment]
```
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.glass.ui.win.WinAccessible
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication.createAccessible(WinApplication.java:298)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at javafx.scene.Scene.getAccessible(Scene.java:6493)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2988)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1390)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.View.getAccessible(View.java:1112)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_View_getAccessible_208bf9d5e8902251a899fb9f0c818944d597913d(JNIJavaCallWrappers.java:0)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at java.lang.Thread.run(Thread.java:833)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Sun Apr 21 19:58:06 PKT 2024][INFO] [SUB] 	at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)
```
Hi, any solution now?

Too much stac traces on the console is the pain in the head, Someone can't focus on the main error, here and there is same duplated error!

**Comment by ctoabidmaqbool1** [comment]
Too much same type of errors is a pain to head, someone can't foucs on main issue, any solution yet!

```
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: com.sun.glass.ui.win.WinAccessible.GetPatternProvider(I)J
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1247)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1232)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:412)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinAccessible._initIDs(WinAccessible.java)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinAccessible.<clinit>(WinAccessible.java:72)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication.createAccessible(WinApplication.java:298)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at javafx.scene.Scene.getAccessible(Scene.java:6493)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2988)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1390)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.View.getAccessible(View.java:1112)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_View_getAccessible_208bf9d5e8902251a899fb9f0c818944d597913d(JNIJavaCallWrappers.java:0)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at java.lang.Thread.run(Thread.java:833)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Mon Apr 22 19:35:47 PKT 2024][INFO] [SUB] 	at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)

```
