### ISSUE TITLE
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/gluonfx-maven-plugin#280]
[My code](https://github.com/EvokeAngle/client_serviceloader/blob/master/service-consumer/src/main/java/serviceconsumer/Main.java) is as follows：
```java
String temp = "{\"age\":22,\"name\":\"A\"}";
Person person = JSON.parseObject(temp, Person.class);
System.out.println(person);

```
pom.xml as flows :
```xml
                <dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.75</version>
		</dependency>
...
                <reflectionList>
                       <list>com.alibaba.fastjson.JSON</list>
                       <list>bean.Person</list>
                 </reflectionList>
```
after mvn clean client:buid,there is nothing wrong ,but mvn client:run,
```java
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
    at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
    at java.lang.ClassLoader.defineClass1(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
    at com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory.createJavaBeanDeserializer(ASMDeserializerFactory.java:89)
    at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:1082)
    at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:888)
    at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:593)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:691)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:395)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:299)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:572)
    at serviceconsumer.Main.start(Main.java:43)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java:101)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
```

**Comment by EvokeAngle** [comment]
Runs normally in the IntelliJ idea

**Comment by jperedadnr** [comment]
There is already an open [issue](https://github.com/oracle/graal/issues/3059) in GraalVM with the same stacktrace.

**Comment by jperedadnr** [comment]
Closing this issue due to lack of activity
