### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.ibatis.session.AutoMappingUnknownColumnBehavior

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/gluonfx-maven-plugin#287]
pom.xml :
```
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.4.1</version>
        </dependency>
    ...
<reflectionList>
    ...
     <list>org.apache.ibatis.session.AutoMappingUnknownColumnBehavior</list>
    ...

</reflectionList>
```
when i run 'mvn client:run ',Console output:
```
Exception in thread "HMIBrowserPictureRefreshTask" java.lang.NoClassDefFoundError: Could not initialize class org.apache.ibatis.session.AutoMappingUnknownColumnBehavior
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:215)
        at org.apache.ibatis.session.Configuration.<init>(Configuration.java:121)
        at org.apache.ibatis.builder.xml.XMLConfigBuilder.<init>(XMLConfigBuilder.java:85)
        at org.apache.ibatis.builder.xml.XMLConfigBuilder.<init>(XMLConfigBuilder.java:69)
        at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:49)
        at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:36)
```

my code is: 
```
this.session = new SqlSessionFactoryBuilder().build(reader).openSession();
```

what can i do for this problem? thanks

**Comment by jperedadnr** [comment]
You might need more related classes in the reflection list. For instance, see there is an inner class [`LogHolder`](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehavior.java#L86), so you will need it too:

```
<reflectionList>
    ...
     <list>org.apache.ibatis.session.AutoMappingUnknownColumnBehavior</list>
    <list>org.apache.ibatis.session.AutoMappingUnknownColumnBehavior$LogHolder</list>
    ...

</reflectionList>
```

It is better if you run the native agent to find if what classes are required, adding this to the `javafx-maven-plugin`:

```
<options>
    <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
</options>
```

Run `mvn javafx:run` and then you will find the config files under `src/main/resources/META-INF/native-image`, with the info about the reflection classes.

**Comment by jperedadnr** [comment]
Closing due to lack of activity
