### ISSUE TITLE
Could not compile project with custom Attach plugin e.g. error: No enum constant com.gluonhq.attach.AttachService.*

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/gluonfx-maven-plugin#354]
I have made a new custom plugin of [Attach](https://github.com/gluonhq/attach) and give it name of hellofx. Everything is okay.

But when I use my custom plugin in a new sample project and try to native compile e.g. `mvn clean -Pandroid gluonfx:compile` it gives me error:

```
mvn clean -Pandroid gluonfx:compile
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellogluon ---
[INFO] Deleting /mnt/d/NetBeansProjects/git-projects/my-hello-gluon-ci/target
[INFO]
[INFO] >>> gluonfx-maven-plugin:1.0.2:compile (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /mnt/d/NetBeansProjects/git-projects/my-hello-gluon-ci/target/classes
[INFO]
[INFO] <<< gluonfx-maven-plugin:1.0.2:compile (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.2:compile (default-cli) @ hellogluon ---
java.lang.RuntimeException: Invalid name for Attach service: hellofx from list of services: accelerometer, audio, audio-recording, augmented-reality, ba
rcode-scan, battery, ble, browser, cache, compass, connectivity, device, dialer, display, in-app-billing, keyboard, lifecycle, local-notifications, magn
etometer, orientation, pictures, position, push-notifications, runtime-args, settings, share, statusbar, storage, vibration, video
        at com.gluonhq.attach.AttachServiceDefinition.<init>(AttachServiceDefinition.java:53)
        at com.gluonhq.attach.AttachArtifactResolver.lambda$findArtifactsForTarget$1(AttachArtifactResolver.java:64)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1033)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.gluonhq.attach.AttachArtifactResolver.findArtifactsForTarget(AttachArtifactResolver.java:77)
        at com.gluonhq.NativeBaseMojo.getAttachDependencies(NativeBaseMojo.java:261)
        at com.gluonhq.NativeBaseMojo.getClasspathElements(NativeBaseMojo.java:218)
        at com.gluonhq.NativeBaseMojo.getProjectClasspath(NativeBaseMojo.java:209)
        at com.gluonhq.NativeBaseMojo.createSubstrateConfiguration(NativeBaseMojo.java:154)
        at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:149)
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:53)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalArgumentException: No enum constant com.gluonhq.attach.AttachService.HELLOFX
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at com.gluonhq.attach.AttachService.valueOf(AttachService.java:39)
        at com.gluonhq.attach.AttachServiceDefinition.<init>(AttachServiceDefinition.java:48)
        ... 39 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.384 s
[INFO] Finished at: 2021-07-08T12:34:05+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.2:compile (default-cli) on project hellogluon: Error: Invalid name for Attach servic
e: hellofx from list of services: accelerometer, audio, audio-recording, augmented-reality, barcode-scan, battery, ble, browser, cache, compass, connect
ivity, device, dialer, display, in-app-billing, keyboard, lifecycle, local-notifications, magnetometer, orientation, pictures, position, push-notificati
ons, runtime-args, settings, share, statusbar, storage, vibration, video: No enum constant com.gluonhq.attach.AttachService.HELLOFX -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I think because it's not listed here [gluonfx-maven-plugin/src/main/java/com/gluonhq/attach/AttachService.java](https://github.com/gluonhq/gluonfx-maven-plugin/blob/master/src/main/java/com/gluonhq/attach/AttachService.java).

How can i solve this?

Should with every new custom attach plugin gluonfx-mobile-plugin need to be build with included plugin?

**Comment by abhinayagarwal** [comment]
Hi @ctoabidmaqbool ,

We are aware of this limitation and are currently discussing on what would be the best solution moving forward. If you have any feedback please feel free to share.

**Comment by mipastgt** [comment]
I'd like to be able to build custom native services independently from attach. I don't understand why this special treatment of attach is needed anyway. Is it just the handling of the classifier by the gluonfx plugins?

**Comment by abhinayagarwal** [comment]
@mipastgt Yes, that's correct.

**Comment by mipastgt** [comment]
As far as I understand the issue, at least for Maven, the classifier could be much easier handled directly in maven via profiles. The way it is handled currently by the gluonfx plugin does not work well in eclipse anyway and just causes a very strange maven setup for me. I don't know enough about gradle and IDEA to judge the situation there.

**Comment by abhinayagarwal** [comment]
GluonFX plugin helps [get rid of profiles](https://github.com/gluonhq/gluon-samples/commit/a32f3e168371202cd87526624a79d5a759ea07fd), which the developer otherwise would have to handle themselves.

**Comment by mipastgt** [comment]
Yes, but the attempt to get rid of profiles breaks Eclipse. The Eclipse maven plugin does not know anything about the fiddling the gluonfx maven plugin does with the classifier. Therefore I have to manually add a desktop profile to fix that. You guys obviously don't use Eclipse anymore :-(

**Comment by johanvos** [comment]
This is now documented at  https://docs.gluonhq.com/samples/gonative/
