### ISSUE TITLE
Fails to execute runagent goal in Eclipse

### ISSUE THREAD

**Issue by marinier** [gluonhq/gluonfx-maven-plugin#355]
I'm updating our code to replace `client-maven-plugin` version `0.1.39` with `gluonfx-maven-plugin` `1.0.3`. Previously we would run the desktop (non-native) version using the `javafx-maven-plugin`'s `javafx:run` goal. However I see in the documentation that since `0.1.37` we don't need to do that and instead we can now run `gluonfx-maven-plugin`'s `gluonfx:runagent` goal instead.

However, when I tried this in Eclipse 2021-06 (on Windows 10 with Java 11), I get this warning and error:

```
[WARNING] No JavaFX plugin found
org.apache.maven.plugin.MojoExecutionException: No JavaFX plugin found
	at com.gluonhq.NativeRunAgentMojo.lambda$execute$2(NativeRunAgentMojo.java:138)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at com.gluonhq.NativeRunAgentMojo.execute(NativeRunAgentMojo.java:135)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.899 s
[INFO] Finished at: 2021-07-16T12:30:03-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:runagent (default-cli) on project <my-project>: Execution default-cli of goal com.gluonhq:gluonfx-maven-plugin:1.0.3:runagent failed: ${maven.home} is not specified as a directory: 'C:\<path-to-my-project>\EMBEDDED'. -> [Help 1]
```

(where <my project> and <path-to-my-project> are actual legitimate values).

The directory it specifies, `'C:\<path-to-my-project>\EMBEDDED'` is indeed not a directory (it doesn't exist at all). The "EMBEDDED" part is suspicious -- the only place that appears is in the Eclipse launch configuration:

![image](https://user-images.githubusercontent.com/535004/125980716-d870e778-0d6f-47e8-b537-0a540419d358.png)

It seems like somehow that is getting mangled with the project directory?

**Comment by marinier** [comment]
I should mention that it runs fine from the command line, so long as I have the javafx plugin configured in my pom. (It's not clear to me why I need to do that, as the gluonfx plugin should have all the information it needs to configure the javafx plugin itself, but I guess that's a separate issue).
