### ISSUE TITLE
Linux aarch64 no longer works

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#384]
Using the latest `1.0.9-SNAPSHOT` version.

Raspberry Pi 0 2 W - 64 Bit Raspberry Pi OS

Console Mode using Gluon FB driver:

```
pi@pi02w:~/stream-pi-client $ ./run_console
Main



determineCpuFeaures
Nov 01, 2021 11:59:24 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @130cfc47'
Prism pipeline init order: es2 sw 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
WARNING: java.lang.UnsatisfiedLinkError
In JNI_OnLoad_prism_es2
System.loadLibrary(prism_es2_monocle) succeeded
        succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
WARNING: java.lang.UnsatisfiedLinkError
System.loadLibrary(glass_monocle) succeeded
[GluonDRM] use GPU at /dev/dri/card0 and display id -1
S0 NOT defined: 
[GluonDRM] We have 2 connectors
[GluonDRM] ID for connector[0] = 32, width = 1024 and height = 600
[GluonDRM] Height was 0 and is now 600
[GluonDRM] ID for connector[1] = 32, width = 1024 and height = 600
eglinit ok 
eglbind ok 
eglCreateWindowSurface called
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
WARNING: java.lang.UnsatisfiedLinkError
System.loadLibrary(glass) succeeded
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:181)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

Looks like its trying to use desktop mode for some reason ? (because of the `...gtk.GtkApplication...`) 

I am running this command:
```
./client -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.lcdtext=false -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dmonocle.platform=EGL -Degl.displayid=$DISPLAY_CARD0
```

On Desktop Mode it works, but it crashes sometime when I try to load ANY CONTENT WITH FOREIGN NON LATIN glyphs.
```
WARNING: java.lang.UnsatisfiedLinkError
cachePangoGlyphStringFields error: JNI exception or tmpClass == NULL
```

I searched about it and found [this](https://openjdk.github.io/cr-archive/jfx/249/webrev.03/modules/javafx.graphics/src/main/native-font/pango.c.html).

**Comment by rnayabed** [comment]
If you want to try it out :

Client aarch64 executable:  https://github.com/stream-pi/client/releases/download/1.0.0-EA%2B4-SNAPSHOT/stream-pi-client-linux-aarch64-1.0.0-EA+4-SNAPSHOT-native-executable.zip

Using this script:

```
curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash -s -- -d https://github.com/stream-pi/client/releases/download/1.0.0-EA%2B4-SNAPSHOT/stream-pi-client-linux-aarch64-1.0.0-EA+4-SNAPSHOT-native-executable.zip
```

is the most recommended as it will add touch support to the pi without having to run javafx as root.

**Comment by jperedadnr** [comment]
You need to include `-Dglass.platform=Monocle` 
See for reference: https://github.com/gluonhq/gluon-samples/blob/master/HelloPi/pom.xml#L69

**Comment by rnayabed** [comment]
Oops. Thank you!, it fixed it
