### ISSUE TITLE
Application not quiting on failed DRM init

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#385]
On standard JVM, while using Gluon's DRM library, the JVM crashes (as expected), when using the incorrect card.

Currently I have the simple following script, to try testing with both `card0` and `card1` on a Raspberry Pi 4:

```
cd "${0%/*}"
export ENABLE_GLUON_COMMERCIAL_EXTENSIONS=true
export DISPLAY_CARD0=/dev/dri/card0
export DISPLAY_CARD1=/dev/dri/card1 # For Raspberry Pi 4

if ! ./client -Dglass.platform=Monocle -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true>
        echo failed to launch using card0, trying to launch using card1

        if ! ./client -Dglass.platform=Monocle -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verb>
                echo failed to launch using card1. Is your KMS driver turned on?
        else
                echo success using card1
        fi
else
        echo success using card0
fi
```

This script works perfectly when using standard JVM instead of gluonfx for aarch64 -> if the command with `card0` fails, it tries using `card1`, and it succeeds.

However, the native image does not exit after failing to init, which blocks further progress of the script and the app is unable to start !

Here is the output when using the incorrect card on aarch64 native image (Raspberry Pi 4 2GB with Pi OS 64 bit):

```
pi@pi4b:~/stream-pi-client $ ./run_console 
Main



determineCpuFeaures
Nov 14, 2021 11:12:06 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2f09e6b2'
Prism pipeline init order: es2 sw 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
WARNING: java.lang.UnsatisfiedLinkError
In JNI_OnLoad_prism_es2
System.loadLibrary(prism_es2_monocle) succeeded
        succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
WARNING: java.lang.UnsatisfiedLinkError
System.loadLibrary(glass_monocle) succeeded
[GluonDRM] use GPU at /dev/dri/card1 and display id -1
S0 NOT defined: 
[GluonDRM] Device /dev/dri/card1 could be opened, but has no drm capabilities.eglinit failed 
eglbind ok 
GraphicsPipeline.createPipeline failed for com.sun.prism.es2.ES2Pipeline
java.lang.ExceptionInInitializerError
        at java.lang.Class.ensureInitialized(DynamicHub.java:552)
        at java.lang.Class.forName(DynamicHub.java:1436)
        at java.lang.Class.forName(DynamicHub.java:1408)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.IllegalArgumentException: Could not create an EGLChooseConfig
        at com.sun.glass.ui.monocle.EGLAcceleratedScreen.<init>(EGLAcceleratedScreen.java:52)
        at com.sun.glass.ui.monocle.EGLPlatform.getAcceleratedScreen(EGLPlatform.java:79)
        at com.sun.prism.es2.MonocleGLFactory.initialize(MonocleGLFactory.java:107)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:76)
        ... 9 more
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
WARNING: java.lang.UnsatisfiedLinkError
System.loadLibrary(prism_sw) succeeded
(X) Got class = class com.sun.prism.sw.SWPipeline
Initialized prism pipeline: com.sun.prism.sw.SWPipeline
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
requested number of screens, return 0
RenderJob.run: internal exception
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.util.Arrays$ArrayList.get(Arrays.java:4351)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1310)
        at com.sun.glass.ui.Screen.getMainScreen(Screen.java:59)
        at com.sun.prism.sw.SWPipeline.getDefaultResourceFactory(SWPipeline.java:83)
        at com.sun.prism.GraphicsPipeline.getDefaultResourceFactory(GraphicsPipeline.java:151)
        at com.sun.javafx.tk.quantum.QuantumRenderer.lambda$createResourceFactory$2(QuantumRenderer.java:163)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)




```

As you can see, it throws an exception as expected but does not stop/exit.

Hence, this should crash/exit. 

Another alternative method would be to atleast have an "auto detection" in the gluon DRM library. It is fairly easy to pull off, itll try using every `card<X>` in `/dev/dri` until all fails or atleast one succeeds.

However, I am unable to edit or do anything since the Gluon DRM library is not opensource. Hence i decided to open this issue!

**Comment by rnayabed** [comment]
I was able to fix this issue by changing the script. New script can be checked [here](https://github.com/stream-pi/client/blob/master/assets/launchers/arm-jvm/run_console).

The script now goes to the directory `/sys/class/drm` and searches the number of files whose name starts with `card0`. If there are more than 1 files that start with name `card0`, the script chooses that card. Otherwise, if it sees there are more than two files with the name `card1`, it will choose that card. If none of them are true, it means KMS is missing. 

The logic behind this is that when a particular card (`card0` or `card1`) is chosen, there are more than 1 files present in the `/sys/class/drm` folder for that card. I am not experienced that much with KMS, but it looks like the extra file has something to do with the display connected.

For example, right now lets say the system has chosen `card0` to be the card used for KMS purposes, instead of `card1`. Then the contents of `/sys/class/drm` will be: 

```
pi@pi4b64:~/stream-pi-client $ ls /sys/class/drm
card0  card0-HDMI-A-1  card1  renderD128  version
```

@jperedadnr maybe a logic inspired by this can be leveraged in the DRM library?

**Comment by rnayabed** [comment]
Not closing the original issue since the problem still remains (application does not quit when it fails)
