### ISSUE TITLE
issues on Mac os x for goal mvn clean client:compile:  Error: type is not available in this platform: com.oracle.svm.hosted.ImageClassLoade

### ISSUE THREAD

**Issue by protid** [gluonhq/gluonfx-maven-plugin#39]
Hello, i'am testing gluonhq for a javafx 11 application, i already installed xcode, JDK 11, when i run it from IDE Intellij it works but when i try to run it as native app, i got this errors:

Is there any solution?

### LOG ERROR
` Omega :: host triplet = x86_64-macos-macos
Omega :: target triplet = x86_64-macos-macos
 [POS:94514]    classlist:  34,356.24 ms
 WARNING: An illegal reflective access operation has occurred
 WARNING: Illegal reflective access by com.oracle.svm.util.ReflectionUtil (file:/Users/msadi/.gluon/omega/graalLibs/20.0.0-ea+12/bundle/lib/svm/builder/pointsto.jar) to field java.nio.file.Files$FileTypeDetectors.installedDetectors
 WARNING: Please consider reporting this to the maintainers of com.oracle.svm.util.ReflectionUtil
 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
 WARNING: All illegal access operations will be denied in a future release
 [POS:94514]        (cap):   1,947.86 ms
 [POS:94514]        setup:   3,741.15 ms
 Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.objectFieldOffset(Class, String) was detected in the static initializer of jdk.internal.misc.InnocuousThread. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.objectFieldOffset(Class, String) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
 Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.objectFieldOffset(Class, String) was detected in the static initializer of jdk.internal.misc.InnocuousThread. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.objectFieldOffset(Class, String) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
 [POS:94514]     analysis:  18,788.94 ms
 Warning: Aborting stand-alone image build. Unsupported features in 2 methods
 Detailed message:
 Error: type is not available in this platform: com.oracle.svm.hosted.ImageClassLoader$1
 Trace: 	object java.lang.Class[]
 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 Error: type is not available in this platform: com.oracle.svm.jni.hosted.JNINativeCallWrapperMethod
 Trace: 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. Unsupported features in 2 methods
 Detailed message:
 Error: type is not available in this platform: com.oracle.svm.hosted.ImageClassLoader$1
 Trace: 	object java.lang.Class[]
 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 Error: type is not available in this platform: com.oracle.svm.jni.hosted.JNINativeCallWrapperMethod
 Trace: 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 	at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:208)
 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:218)
 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:739)
 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
 Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
 Detailed message:
 Error: type is not available in this platform: com.oracle.svm.hosted.ImageClassLoader$1
 Trace: 	object java.lang.Class[]
 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 Error: type is not available in this platform: com.oracle.svm.jni.hosted.JNINativeCallWrapperMethod
 Trace: 	object java.lang.invoke.MethodType
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
 	object java.util.concurrent.ConcurrentHashMap$Node
 	object java.util.concurrent.ConcurrentHashMap$Node[]
 	object java.util.concurrent.ConcurrentHashMap
 	object java.lang.invoke.MethodType$ConcurrentWeakInternSet
 	method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
 Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
 	at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
 	at java.base@12.0.2/java.lang.invoke.MethodType.methodType(MethodType.java:212)
 	at java.base@12.0.2/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
 	at java.base@12.0.2/java.lang.invoke.VarHandleLongs$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleLongs.java:57)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
 	at java.base@12.0.2/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
 	at java.base@12.0.2/java.lang.String.valueOf(String.java:3042)
 	at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:745)
 	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:551)
 	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
 	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:133)
 	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:690)
 	... 8 more
java.lang.RuntimeException: Error compiling
	at com.gluonhq.omega.SVMBridge.compile(SVMBridge.java:311)
	at com.gluonhq.omega.target.MacosTargetProcess.compileApplication(MacosTargetProcess.java:407)
	at com.gluonhq.omega.target.AbstractTargetProcess.compile(AbstractTargetProcess.java:318)
	at com.gluonhq.omega.Omega.nativeCompile(Omega.java:72)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:77)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)`

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with a recent version of the plugin (1.0.10)
