### ISSUE TITLE
java.net.NoSuchFieldError: java.net.Inet6Address.cached_scope_id on Android

### ISSUE THREAD

**Issue by CallumMackenzie** [gluonhq/gluonfx-maven-plugin#417]
I am fairly new to using Gluon/GraalVM and when running my application on android I get this exception:
```
Exception in thread "Thread-6" java.lang.NoSuchFieldError: java.net.Inet6Address.cached_scope_id
at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1207)
at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:434)
at java.net.Inet6Address.init(Inet6Address.java)
at java.net.Inet6Address.<clinit>(Inet6Address.java:369)
at java.lang.Class.ensureInitialized(DynamicHub.java:510)
at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:355)
at java.net.PlainSocketImpl.initProto(PlainSocketImpl.java)
at java.net.PlainSocketImpl.<clinit>(PlainSocketImpl.java:43)
at java.lang.Class.ensureInitialized(DynamicHub.java:510)
at java.net.Socket.setImpl(Socket.java:523)
at java.net.Socket.<init>(Socket.java:88)
at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:162)
at sun.security.ssl.BaseSSLSocketImpl.<init>(BaseSSLSocketImpl.java:61)
at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:118)
at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:72)
at javax.net.ssl.SSLContextSpi.getDefaultSocket(SSLContextSpi.java:163)
at javax.net.ssl.SSLContextSpi.engineGetSupportedSSLParameters(SSLContextSpi.java:212)
at javax.net.ssl.SSLContext.getSupportedSSLParameters(SSLContext.java:471)
at jdk.internal.net.http.HttpClientImpl.getDefaultParams(HttpClientImpl.java:335)
at jdk.internal.net.http.HttpClientImpl.<init>(HttpClientImpl.java:300)
at jdk.internal.net.http.HttpClientImpl.create(HttpClientImpl.java:253)
at jdk.internal.net.http.HttpClientBuilderImpl.build(HttpClientBuilderImpl.java:135)
at java.net.http.HttpClient.newHttpClient(HttpClient.java:158)
at {my requesting class}
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```
of which the request code looks like
```java
HttpClient client = HttpClient.newHttpClient();
Builder requestBuilder = HttpRequest.newBuilder().uri(URI.create(this.endpoint));
requestBuilder.POST(BodyPublishers.ofString(gson.toJson(this.body)));
client.sendAsync(requestBuilder.build(), BodyHandlers.ofString());
```
The program runs fine when compiled natively for windows.

I am using Gluon's GraalVM release 22.0.0.3 for JDK 11 and from what I have seen from [this issue](https://github.com/gluonhq/gluonfx-maven-plugin/issues/413) the field `cached_scope_id` should not be present on in the `java.net.Inet6Address` class. My `reflectionconfig-aarch64-android.json` file also validates this, containing the entries :
```json
{
    "name": "java.net.Inet6Address",
    "fields": [{ "name":"holder6", "allowUnsafeAccess":true }]
},
{
    "name": "java.net.Inet6AddressImpl",
    "methods": [{ "name":"<init>", "parameterTypes":[] }]
}
```
Which confuses me as I can't think of a reason that the executable would attempt to reflectively access the nonexistant `cached_scope_id` field.

If it is relevant, I am building using Debian 9 and deploying to an android 10 device.

**Comment by javateer** [comment]
I was using the following before:

`GRAALVM_HOME=/opt/graalvm-svm-linux-gluon-21.2.0-dev`

`<groupId>com.gluonhq</groupId>`
`<artifactId>gluonfx-maven-plugin</artifactId>`
`<version>1.0.0</version>`

I saw this same error message after upgrading as so:

`GRAALVM_HOME=/opt/graalvm/graalvm-svm-java11-linux-gluon-22.0.0.3-Final`

That error went away for me after I subsequently also upgraded as so:

`<groupId>com.gluonhq</groupId>`
`<artifactId>gluonfx-maven-plugin</artifactId>`
`<version>1.0.12</version>`

Actually, it didn't make my blocker go away. I see a new, different issue:

> No message found for 1.not.found.as.resource

But still, I hope this helps you with your progress.

**Comment by marinier** [comment]
We are discussing a very similar issue here: https://github.com/gluonhq/substrate/issues/1120
