### ISSUE TITLE
getStreamSize() not found

### ISSUE THREAD

**Issue by perNyfelt** [gluonhq/gluonfx-maven-plugin#423]
I get the following error when running mvn gluonfx:build
```
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] Error: Error parsing JNI configuration in /home/per/project/myproject/target/gluonfx/x86_64-linux/gvm/jniconfig-x86_64-linux.json:
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] Method com.sun.media.jfxmedia.locator.ConnectionHolder.getStreamSize() not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in /home/per/project/myproject/target/gluonfx/x86_64-linux/gvm/jniconfig-x86_64-linux.json:
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] Method com.sun.media.jfxmedia.locator.ConnectionHolder.getStreamSize() not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:135)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:86)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:88)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:128)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$14(NativeImageGenerator.java:802)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:802)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:534)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
[Fri Apr 22 16:13:24 CEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
```
`mvn javafx:run` works without problem
### Dependencies
- javafx version: 18
- java version: 
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)
- gluonfx-maven-plugin version: 1.0.13
- OS: Linux Mint 20.3

A minimal example project displaying the issue can be found here: https://github.com/perNyfelt/javafx-native-example

Is there anything I can do (config etc.) get past the issue?

**Comment by perNyfelt** [comment]
Adding the following config fixed the issue:
```
                    <javaStaticSdkVersion>17.0.2</javaStaticSdkVersion>
                    <javafxStaticSdkVersion>18</javafxStaticSdkVersion>
```
