### ISSUE TITLE
java.lang.NullPointerException when running gluonfx:package on macOS

### ISSUE THREAD

**Issue by salmonb** [gluonhq/gluonfx-maven-plugin#429]
hi,

I'm getting the following error when running the gluonfx:package goal on macOS: 

```
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because the return value of "java.nio.file.Path.getParent()" is null
	at com.gluonhq.substrate.util.XcodeUtils.<init>(XcodeUtils.java:71)
	at com.gluonhq.substrate.util.macos.InfoPlist.<init>(InfoPlist.java:86)
	at com.gluonhq.substrate.target.MacOSTargetConfiguration.createInfoPlist(MacOSTargetConfiguration.java:196)
	at com.gluonhq.substrate.target.MacOSTargetConfiguration.createAppBundle(MacOSTargetConfiguration.java:184)
	at com.gluonhq.substrate.target.MacOSTargetConfiguration.packageApp(MacOSTargetConfiguration.java:147)
	at com.gluonhq.substrate.SubstrateDispatcher.nativePackage(SubstrateDispatcher.java:461)
	at com.gluonhq.NativePackageMojo.execute(NativePackageMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

According to a code analysis of XcodeUtils, it first evaluates this command line, which in my case returns the following result:
```
$ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

and XcodeUtils.java:71 calls 6 times getParent() on this path, which unfortunately has only 5 folder levels here, that's why a NPE is raised.

**Comment by webdancer** [comment]
Hi, I'm getting the exact same error on my MacBook Pro which runs on Monterey 12.4. The command `xcrun --sdk macosx --show-sdk-path` also displays `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`. Could you please fix this bug?

**Comment by jperedadnr** [comment]
You _need_ Xcode, see https://docs.gluonhq.com/#platforms_macos, command tools are not enough

**Comment by webdancer** [comment]
But I have Xcode installed on my machine, not just the command tools, and yet still get this error

**Comment by jperedadnr** [comment]
Ok, then there is already this issue: https://github.com/gluonhq/substrate/issues/978 
You just need to switch to Xcode with `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by salmonb** [comment]
Thanks, this solves my problem too 😃 

I would suggest however to integrate a test in XcodeUtils that checks the Xcode path and raises an exception with a message proposing to run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` if it's not the expected Xcode path, rather than just a NPE. That would help other people facing the same problem.

I'm closing the issue btw.

Thank you!
