### ISSUE TITLE
NoSuchMethodError: java.lang.Throwable.toString() loading sqlite on android

### ISSUE THREAD

**Issue by ianopolous** [gluonhq/gluonfx-maven-plugin#447]
Thank you for Gluon. It is awesome!

I'm trying to load sqlite in an android app. I'm using the latest sqlite (3.39.3.0) which explicitly supports android. 

I've added the following to my config:
```xml
                    <resourcesList>
                      <list>.*\\.so$</list>
                    </resourcesList>
                    <jniList>
                      <list>org.sqlite.core.DB</list>
                      <list>org.sqlite.core.NativeDB</list>
                      <list>org.sqlite.BusyHandler</list>
                      <list>org.sqlite.Function</list>
                      <list>org.sqlite.ProgressHandler</list>
                      <list>org.sqlite.Function$Aggregate</list>
                      <list>org.sqlite.Function$Window</list>
                      <list>org.sqlite.core.DB$ProgressObserver</list>
                    </jniList>
                    <nativeImageArgs>
                      <arg>-H:IncludeResources='.*org/sqlite/native/Linux-Android/aarch64/libsqlitejdbc.so$'</arg>
                    </nativeImageArgs>
```
Before loading sqlite I set this parameter to tell it that it's on android:
> System.setProperty("java.runtime.name", "android");

When starting sqlite it throws the following trying to load the shared library:
```
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.lang.Thread.run(Thread.java:833)
 	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
 	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 Caused by: java.lang.NoSuchMethodError: java.lang.Throwable.toString()Ljava/lang/String;
 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1247)
 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1232)
 	at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:412)
 	at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
 	at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:69)
 	at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:126)
 	at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:186)
 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:142)
 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:101)
 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:54)
 	at java.lang.Runtime.load0(Runtime.java:755)
 	at java.lang.System.load(System.java:1953)
 	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
 	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
 	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
 	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
 	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
 	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
 	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
 	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
 	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
 	at org.sqlite.JDBC.createConnection(JDBC.java:104)
 	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:440)
 	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:432)
 	at peergos.server.util.Sqlite.build(Sqlite.java:16)
 	at peergos.server.Builder.getDBConnector(Builder.java:111)
 	at org.peergos.sample.Main.startServer(Main.java:77)
 	at org.peergos.sample.Main.start(Main.java:38)
 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
 	at java.security.AccessController.executePrivileged(AccessController.java:169)
 	at java.security.AccessController.doPrivileged(AccessController.java:399)
 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
 	... 3 more
```

I tried adding java.lang.Throwable to jniList config, but then it won't compile.

Any pointers would be extremely appreciated.

**Comment by ianopolous** [comment]
I was wrong. The build failure after adding Throwable to jniList must have been a spurious error. It works now!!

**Comment by Hitzui** [comment]
dear, I have tried to follow your instructions, and in my case, it continues to present the same error, if it is possible to help with an example code, I will greatly appreciate it, greetings.

**Comment by ianopolous** [comment]
@Hitzui Our code is at https://github.com/peergos/mobile
