### ISSUE TITLE
Error linking

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#45]
I tried to compile and link a larger application but all I got was this after 13 minutes:

    Omega :: host triplet = x86_64-macos-macos
    Omega :: target triplet = x86_64-macos-macos
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB] ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB] Undefined symbols for architecture x86_64:
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB]   "_JVM_GetClassContext", referenced from:
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB]       _Java_java_lang_SecurityManager_getClassContext in libjava.a(SecurityManager.o)
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB] ld: symbol(s) not found for architecture x86_64
    [Mi. Sep. 18 13:22:38 MESZ 2019][INFORMATION] [SUB] clang: error: linker command failed with exit code 1 (use -v to see invocation)
    java.lang.RuntimeException: Error linking
        at com.gluonhq.omega.target.MacosTargetProcess.link(MacosTargetProcess.java:501)
        at com.gluonhq.omega.Omega.nativeLink(Omega.java:86)
        at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:54)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

Any idea what that means or how that could be prevented?

**Comment by maxum2610** [comment]
Just to put in my two cents, I had exactly the same problem sporadically when running:

mvn clean client:compile 

followed by:

mvn client:link

I'm also on OSX, and executing:

mvn clean client:build -e -X      generally works for some reason (-e and -X flags for extended debug info).
You can also run the compilation and link scripts directly: ./compile.sh -e -X    and   ./link.sh
which can be found under: yourprojectdir/target/client/macos-x86_64/gvm/
You can tweek the compile and link scripts if need be.
I've managed to build and run (window shows) and extremely complex application with everything in it but the kitchen sink, but it hangs on a few yet to be resolved issues in openjdk 11 code.

Hope this helps.

**Comment by mipastgt** [comment]
@maxum2610 For me it always fails and the tweeking possibilities do not really help if you have no idea what to tweak :-)

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with a recent version of the plugin (1.0.10)
