### ISSUE TITLE
Native app crashes on Media constructor call with: no jfxmedia in java.library.path

### ISSUE THREAD

**Issue by salmonb** [gluonhq/gluonfx-maven-plugin#451]
hi,

When trying to run an app using javafx-media on Android (I haven't tested yet on iOS), I'm getting the following error:

```
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): Exception in Application start method
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): QuantumRenderer: shutdown
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): Exception in thread "Thread-1" java.lang.RuntimeException: Exception in Application start method
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.lang.Thread.run(Thread.java:833)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): Caused by: java.lang.UnsatisfiedLinkError: no jfxmedia in java.library.path
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:47)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.lang.Runtime.loadLibrary0(Runtime.java:818)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.lang.System.loadLibrary(System.java:1989)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:65)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmediaimpl.NativeMediaManager.lambda$new$0(NativeMediaManager.java:138)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.security.AccessController.executePrivileged(AccessController.java:145)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at java.security.AccessController.doPrivileged(AccessController.java:569)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmediaimpl.NativeMediaManager.<init>(NativeMediaManager.java:108)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmediaimpl.NativeMediaManager$NativeMediaManagerInitializer.<clinit>(NativeMediaManager.java:78)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmediaimpl.NativeMediaManager.getDefaultInstance(NativeMediaManager.java:90)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmedia.MediaManager.canPlayProtocol(MediaManager.java:78)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at com.sun.media.jfxmedia.locator.Locator.<init>(Locator.java:240)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	at javafx.scene.media.Media.<init>(Media.java:393)
[Tue Nov 01 11:51:56 GMT 2022][INFO] [SUB] D/GraalCompiled( 1362): 	...
```

Can this be fixed?

**Comment by salmonb** [comment]
I just tried on iOS today, and I'm getting exactly the same error. So it's not specific to Android. The crash happens on both mobile platforms.

This bug should prevent any app requiring sound or video to run on mobiles.

Did you manage to compile and run SpaceFX on mobiles with Gluon?
