### ISSUE TITLE
Integration of log4j fails with JavaFX in nativerun

### ISSUE THREAD

**Issue by rgerasch** [gluonhq/gluonfx-maven-plugin#457]
Hello,
I tried to include log4j 2.17.1 in a JavaFx application. I also tried with older versions of log4j - without success. 
All mvn phases run ok, but not nativerun.

Command Line
============
mvn gluonfx:nativerun

Output
======
Feb. 05, 2023 9:34:25 PM com.gluonhq.substrate.util.Logger logInfo
INFORMATION: Substrate is tested with the Gluon's GraalVM build which you can find at https://github.com/gluonhq/graal/releases.
While you can still use other GraalVM builds, there is no guarantee that these will work properly with Substrate
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] ==================== RUN TASK ====================
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB] Exception in thread "main" java.lang.ExceptionInInitializerError
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:61)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at hellofx.HelloFX.<clinit>(HelloFX.java:42)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB] Caused by: java.lang.IllegalStateException: java.lang.InstantiationException: org.apache.logging.log4j.message.DefaultFlowMessageFactory
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.spi.AbstractLogger.createDefaultFlowMessageFactory(AbstractLogger.java:246)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.spi.AbstractLogger.<init>(AbstractLogger.java:144)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.status.StatusLogger.<init>(StatusLogger.java:105)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:85)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      ... 2 more
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB] Caused by: java.lang.InstantiationException: org.apache.logging.log4j.message.DefaultFlowMessageFactory
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:639)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at org.apache.logging.log4j.spi.AbstractLogger.createDefaultFlowMessageFactory(AbstractLogger.java:244)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      ... 5 more
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB] Caused by: java.lang.NoSuchMethodException: org.apache.logging.log4j.message.DefaultFlowMessageFactory.<init>()
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:626)
[So. Feb. 05 21:34:25 MEZ 2023][INFORMATION] [SUB]      ... 6 more

Configuration
============
Windows 10,  Maven 3.8.7 ,  Gluon Samples with <gluonfx.maven.plugin.version>1.0.16</gluonfx.maven.plugin.version>
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

steps to reproduce
============
Can be reproduced with any JavaFx App. - i.e. try with the one of the https://github.com/gluonhq/gluon-samples  as I did for this report. I took HelloFx
- add to the pom.xml:
             	\<dependency\>
			\<!-- log4j API --\>
			\<groupId>org.apache.logging.log4j</groupId\>
			\<artifactId>log4j-api</artifactId\>
			\<version>2.17.1</version\>
		\</dependency\>
		\<dependency\>
			\<!-- log4j Implementation --\>
			\<groupId>org.apache.logging.log4j</groupId\>
			\<artifactId>log4j-core</artifactId\>
			\<version>2.17.1</version\>
		\</dependency\>
- add to HelloFx.java
       private static final Logger log = LogManager.getLogger();
       and ...
          public void start(Stage stage) {
		log.info("start");

- run all mvn gluon phases - all ok, but nativerun fails.

Thanks

**Comment by iammmmmmm** [comment]
You can try the combination of slf4j+logback. This combination performs well whether it is nativeRun or packaged and built to Android.

**Comment by ctoabidmaqbool** [comment]
Sometime using latest stable plugins/tools solve the problem:
`com.gluonhq:gluonfx-maven-plugin:1.0.23`, `com.gluonhq.attach:util:4.0.21` and [GraalVM CE Gluon 22.1.0.1-Final](https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final)
