### ISSUE TITLE
issues on macos for goal mvn clean client:compile: UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.core.posix.Java_lang_Process_Supplement

### ISSUE THREAD

**Issue by mbbee** [gluonhq/gluonfx-maven-plugin#46]
compiler has problems with class Process.
native-image from GraalVM compiles without problems!

```
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Warning: Aborting stand-alone image build. com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.core.posix.Java_lang_Process_Supplement
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Detailed message:
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Trace: 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at parsing app//com.oracle.svm.core.posix.Target_java_lang_ProcessHandleImpl.waitForProcessExit0(Target_java_lang_ProcessHandleImpl.java:52)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Call path from entry point to java.lang.ProcessHandleImpl.waitForProcessExit0(long, boolean): 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at app//com.oracle.svm.core.posix.Target_java_lang_ProcessHandleImpl.waitForProcessExit0(Target_java_lang_ProcessHandleImpl.java:52)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base@11.0.2/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:138)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_Runnable_2_0002erun_00028_00029V(generated:0)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.core.posix.Java_lang_Process_Supplement
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Detailed message:
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Trace: 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at parsing app//com.oracle.svm.core.posix.Target_java_lang_ProcessHandleImpl.waitForProcessExit0(Target_java_lang_ProcessHandleImpl.java:52)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] Call path from entry point to java.lang.ProcessHandleImpl.waitForProcessExit0(long, boolean): 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at app//com.oracle.svm.core.posix.Target_java_lang_ProcessHandleImpl.waitForProcessExit0(Target_java_lang_ProcessHandleImpl.java:52)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base@11.0.2/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:138)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_Runnable_2_0002erun_00028_00029V(generated:0)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:208)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:218)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:739)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Tue Sep 24 09:39:07 CEST 2019][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by SergeVil** [comment]
Have the same problem using  "gradle nativeCompile". Is it any workaround or am I missing something?

Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.core.posix.Java_lang_Process_Supplement

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with the latest plugin 1.0.10. Feel free to reopen otherwise.
