### ISSUE TITLE
Wrong resource patterns

### ISSUE THREAD

**Issue by RealThanhpv** [gluonhq/gluonfx-maven-plugin#478]
The build is fine if I delete the resource-configuration file generated by runagent.

```
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB] Error: Resource pattern "javafx.graphics:\Qglass.dll\E"s specifies unknown module javafx.graphics
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Resource pattern "javafx.graphics:\Qglass.dll\E"s specifies unknown module javafx.graphics
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB]      at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB]      at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:354)
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB]      at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB]      at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[Sat Jul 08 01:13:40 ICT 2023][INFO] [SUB]      at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
```

**Comment by negod** [comment]
I got the exact same problem

**Comment by cooper87** [comment]
It should be same as https://github.com/gluonhq/gluonfx-gradle-plugin/issues/178

**Comment by ozkanpakdil** [comment]
I think I am having the same problem, I updated jsons with the same gluon version that I use in [github actions](https://github.com/ozkanpakdil/swaggerific/actions/runs/8702431041/job/23866454637)

https://stackoverflow.com/questions/78177259/gluon-build-problem-specifies-unknown-module-javafx-graphics

still having the same error, it works with regular CE graalvm in linux and win build. 

you can see all in https://github.com/ozkanpakdil/swaggerific
