### ISSUE TITLE
 Couldn't determine GraalVM version

### ISSUE THREAD

**Issue by RealThanhpv** [gluonhq/gluonfx-maven-plugin#489]
I just made a try with  graal-21. I did not work
```
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.20:compile (default-cli) on project app: Error: Fatal Error: java.io.IOException: Couldn't determine GraalVM version -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by westinyang** [comment]
Encountered the same problem

**Comment by tmulle** [comment]
Same here.. looks like the version numbering of 21 is shorter than what the code is trying to parse.
I've seen this elsewhere with the new "21" version number being returned from the graalvm

**Comment by gunnarre** [comment]
This bug is still present:
`java.io.IOException: Couldn't determine GraalVM version
	at com.gluonhq.substrate.model.InternalProjectConfiguration.getGraalVersion(InternalProjectConfiguration.java:136)
	at com.gluonhq.substrate.model.InternalProjectConfiguration.checkGraalVMVersion(InternalProjectConfiguration.java:468)
	at com.gluonhq.substrate.SubstrateDispatcher.<init>(SubstrateDispatcher.java:381)`
java -version gives
`java version "23" 2024-09-17
Java(TM) SE Runtime Environment Oracle GraalVM 23+37.1 (build 23+37-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23+37.1 (build 23+37-jvmci-b01, mixed mode, sharing)
`
