### ISSUE TITLE
Native image locale problem

### ISSUE THREAD

**Issue by Hugolarson** [gluonhq/gluonfx-maven-plugin#490]
Hello,

Running the created native .exe throws this exception.

[Tue Oct 03 10:02:33 CEST 2023][INFO] [SUB] java.util.MissingResourceException: Can't find bundle for base name sun.util.resources.CurrencyNames, locale sv_SE
[Tue Oct 03 10:02:33 CEST 2023][INFO] [SUB]     at java.base@17.0.6/sun.util.resources.Bundles.throwMissingResourceException(Bundles.java:302)
[Tue Oct 03 10:02:33 CEST 2023][INFO] [SUB]     at java.base@17.0.6/sun.util.resources.Bundles.loadBundleOf(Bundles.java:147)
[Tue Oct 03 10:02:33 CEST 2023][INFO] [SUB]     at java.base@17.0.6/sun.util.resources.Bundles.of(Bundles.java:106)
[Tue Oct 03 10:02:33 CEST 2023][INFO] [SUB]     at java.base@17.0.6/sun.util.resources.LocaleData$1.run(LocaleData.java:186)

**Comment by Khithar** [comment]
<nativeImageArgs>
   ...
   <arg>-Duser.language=sv</arg>
   <arg>-H:IncludeLocales=sv,en</arg>
    ...
</nativeImageArgs>

and of course do an agentrun
