### ISSUE TITLE
I want to use mysql in my desktop hobby project and cannot nativerun with maven

### ISSUE THREAD

**Issue by icyhoty2k** [gluonhq/gluonfx-maven-plugin#503]
i get this error
`[INFO] --- gluonfx-maven-plugin:1.0.22:nativerun (default-cli) @ hellofxml ---
[Wed Mar 13 03:09:28 EET 2024][INFO] ==================== RUN TASK ====================
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB] Mar 13, 2024 3:09:28 AM com.sun.javafx.application.PlatformImpl startup
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6b71769e'
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB] Exception in Application start method
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method [Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java)[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.lang.Thread.run(Thread.java:833)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB] Caused by: java.util.MissingResourceException: Can't find bundle for base name hellofx.hello, locale en_US
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at hellofx.HelloFXML.start(HelloFXML.java:47)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.security.AccessController.executePrivileged(AccessController.java:169)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:399)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Runnable_run_16403f8d32adb631126daa893e5e80085c5d6325(JNIJavaCallWrappers.java:0)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
[Wed Mar 13 03:09:28 EET 2024][INFO] [SUB]      ... 3 more`
how to fix it ?

**Comment by icyhoty2k** [comment]
it compiles fine and links fine but cannot gluonfx:nativerun

**Comment by ctoabidmaqbool** [comment]
@icyhoty2k Try to run `gluonfx:runagent` and test your app for all use cases. It will all many native configuration automatically!

can build and run your app e.g. nativerun!
