### ISSUE TITLE
Issues with UI scaling

### ISSUE THREAD

**Issue by xerz-one** [gluonhq/gluonfx-maven-plugin#93]
I've just built a test app with the Gluon Client plugin on Debian Sid, where I've noticed running the application leaves the UI at a low DPI scale by default. I tried adjusting it with `GDK_SCALE=2`, which does resize the main window but (in my small test) also made characters blank and returned [this log](https://github.com/gluonhq/client-maven-plugin/files/4022342/log.txt), with many error messages like this:

```java
cacheFT_MatrixFields error: JNI exception or xx == NULLjava.lang.IllegalArgumentException: Destination region (x=0, y=0, w=11096, h=3700) must fit within texture content bounds (contentWidth=1024, contentHeight=1024)
	at com.sun.prism.impl.BaseTexture.checkUpdateParams(BaseTexture.java:370)
	at com.sun.prism.es2.ES2Texture.update(ES2Texture.java:640)
	at com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:316)
	at com.sun.prism.impl.GlyphCache.render(GlyphCache.java:148)
	at com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2101)
	at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
	at com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
	at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(CacheFilter.java:683)
	at com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:587)
	at com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2377)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2063)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by espectalll** [comment]
Perhaps this ticket makes more sense at [gluonhq/substrate](https://github.com/gluonhq/substrate)?

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with the latest plugin 1.0.10. Feel free to reopen otherwise.
